//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(void);
int64_t _fini(void);
int64_t _GLOBAL__sub_I_main(void);
int64_t _init(void);
int64_t _start(void);
int64_t _Z41__static_initialization_and_destruction_0ii(int64_t a1, int64_t a2);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int64_t function_1003(void);
int64_t function_1030(int64_t * a1, int64_t * a2);
int32_t function_1040(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle);
int64_t function_1050(int64_t * a1, char * a2, int64_t a3);
void function_1060(void);
int64_t function_1070(int64_t a1);
int64_t function_1123(void);
int64_t function_1173(void);
int64_t function_12a3(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1313(void);
int64_t function_131b(void);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1170;
int64_t g2 = 0x1120;
void (*g3)(int64_t *) = NULL;
int64_t g4; // 0x4048
int64_t g5 = 0;
int64_t g6 = 0;
char g7 = 0;
int64_t g8; // 0x4299
int64_t g9 = 0; // rax
int32_t g10;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int64_t _init(void) {
    // 0x1000
    return g9;
}

// Address range: 0x1003 - 0x101b
int64_t function_1003(void) {
    // 0x1003
    int64_t result; // 0x101a
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g10;
    } else {
        result = 0;
    }
    // 0x1016
    return result;
}

// Address range: 0x1030 - 0x1036
int64_t function_1030(int64_t * a1, int64_t * a2) {
    // 0x1030
    return _ZNSirsERi();
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle) {
    // 0x1040
    return __cxa_atexit(func, arg, dso_handle);
}

// Address range: 0x1050 - 0x1056
int64_t function_1050(int64_t * a1, char * a2, int64_t a3) {
    // 0x1050
    return _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc();
}

// Address range: 0x1060 - 0x1066
void function_1060(void) {
    // 0x1060
    __stack_chk_fail();
}

// Address range: 0x1070 - 0x1076
int64_t function_1070(int64_t a1) {
    // 0x1070
    return _ZNSt8ios_base4InitC1Ev();
}

// Address range: 0x1080 - 0x1081
int64_t _start(void) {
    // 0x1080
    int64_t result; // rax
    return result;
}

// Address range: 0x10b0 - 0x10d9
int64_t deregister_tm_clones(void) {
    // 0x10b0
    return 0x4050;
}

// Address range: 0x10e0 - 0x1119
int64_t register_tm_clones(void) {
    // 0x10e0
    return 0;
}

// Address range: 0x1120 - 0x1121
int64_t __do_global_dtors_aux(void) {
    // 0x1120
    int64_t result; // rax
    return result;
}

// Address range: 0x1123 - 0x1161
int64_t function_1123(void) {
    // 0x1123
    if (g7 != 0) {
        // 0x1160
        int64_t result; // rax
        return result;
    }
    if (*(int64_t *)0x3fd0 != 0) {
        // 0x113b
        __cxa_finalize((int64_t *)*(int64_t *)0x4048);
    }
    // 0x1148
    g7 = 1;
    return deregister_tm_clones();
}

// Address range: 0x1170 - 0x1171
int64_t frame_dummy(void) {
    // 0x1170
    int64_t result; // rax
    return result;
}

// Address range: 0x1173 - 0x1179
int64_t function_1173(void) {
    // 0x1173
    return register_tm_clones();
}

// Address range: 0x1179 - 0x1234
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x1181
    int64_t v2; // rdx
    function_1050(&g5, "Enter a positive integer: ", v2);
    int32_t v3; // bp-24
    function_1030(&g6, (int64_t *)&v3);
    int64_t v4 = 0x100000000 * (int64_t)(v3 >> 31) | (int64_t)v3; // 0x11d6
    uint32_t v5 = ((int32_t)(v3 < 0) + v3) / 2; // 0x11cb
    if (v5 < 2) {
      lab_0x11f1:
        // 0x11f1
        function_1050(&g5, "This is a prime number", (int64_t)(v3 < 0));
    } else {
        int32_t v6 = 2;
        int64_t v7; // 0x11d6
        while (true) {
            // 0x11d2
            v7 = v4 % (int64_t)v6;
            int32_t v8 = v6 + 1; // 0x11e5
            if ((int32_t)v7 == 0) {
                // break -> 0x1206
                break;
            }
            if ((int64_t)v8 > (int64_t)v5) {
                goto lab_0x11f1;
            }
            v6 = v8;
        }
        // 0x1206
        function_1050(&g5, "This is not a prime number", v7);
    }
    // 0x1219
    int64_t result; // 0x1233
    if (v1 == __readfsqword(40)) {
        // 0x1219
        result = 0;
    } else {
        // 0x122d
        __stack_chk_fail();
        result = &g10;
    }
    // 0x1232
    return result;
}

// Address range: 0x1234 - 0x127d
// Demangled:     __static_initialization_and_destruction_0(int, int)
int64_t _Z41__static_initialization_and_destruction_0ii(int64_t a1, int64_t a2) {
    // 0x1234
    if ((int32_t)a1 != 1) {
        // 0x127a
        return g9;
    }
    // 0x1248
    if ((int32_t)a2 == 0xffff) {
        // 0x1251
        function_1070(0x4299);
        g9 = __cxa_atexit(g3, &g8, &g4);
    }
    // 0x127a
    return g9;
}

// Address range: 0x127d - 0x1292
int64_t _GLOBAL__sub_I_main(void) {
    // 0x127d
    return _Z41__static_initialization_and_destruction_0ii(1, 0xffff);
}

// Address range: 0x12a0 - 0x12a1
int64_t __libc_csu_init(void) {
    // 0x12a0
    int64_t result; // rax
    return result;
}

// Address range: 0x12a3 - 0x1305
int64_t function_12a3(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x12cc
    if (((int64_t)&g2 - (int64_t)&g1) / 8 != 0) {
        int64_t v1 = 0; // 0x12ed2
        while (v1 + 1 != ((int64_t)&g2 - (int64_t)&g1) / 8) {
            // 0x12e0
            v1++;
        }
    }
    // 0x12f6
    return result;
}

// Address range: 0x1310 - 0x1311
int64_t __libc_csu_fini(void) {
    // 0x1310
    int64_t result; // rax
    return result;
}

// Address range: 0x1313 - 0x1315
int64_t function_1313(void) {
    // 0x1313
    int64_t result; // rax
    return result;
}

// Address range: 0x1318 - 0x1319
int64_t _fini(void) {
    // 0x1318
    int64_t result; // rax
    return result;
}

// Address range: 0x131b - 0x1325
int64_t function_131b(void) {
    // 0x131b
    int64_t result; // rax
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int __cxa_atexit(void(* func)(void *), void * arg, void * dso_handle);
// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// void __stack_chk_fail(void);
// int64_t _ZNSirsERi(void);
// int64_t _ZNSt8ios_base4InitC1Ev(void);
// int64_t _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.2.0)
// Detected language: C++
// Detected functions: 23
// Decompilation date: 2019-11-14 13:56:59
