//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(void);
int64_t _Z4funci(int64_t a1);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int64_t function_1003(void);
int64_t function_10c3(void);
int64_t function_1113(void);
int64_t function_1163(int64_t a1, int64_t a2, int64_t a3);
int64_t function_11d3(void);
int64_t function_11db(void);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1110;
int64_t g2 = 0x10c0;
int64_t g3 = 0;
int64_t g4 = 0; // rax
int32_t g5;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int64_t _init(void) {
    // 0x1000
    return g4;
}

// Address range: 0x1003 - 0x101b
int64_t function_1003(void) {
    // 0x1003
    int64_t result; // 0x101a
    if (*(int64_t *)0x3ff0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g5;
    } else {
        result = 0;
    }
    // 0x1016
    return result;
}

// Address range: 0x1020 - 0x1021
int64_t _start(void) {
    // 0x1020
    int64_t result; // rax
    return result;
}

// Address range: 0x1050 - 0x1079
int64_t deregister_tm_clones(void) {
    // 0x1050
    return &g3;
}

// Address range: 0x1080 - 0x10b9
int64_t register_tm_clones(void) {
    // 0x1080
    return 0;
}

// Address range: 0x10c0 - 0x10c1
int64_t __do_global_dtors_aux(void) {
    // 0x10c0
    int64_t result; // rax
    return result;
}

// Address range: 0x10c3 - 0x1101
int64_t function_10c3(void) {
    // 0x10c3
    if (*(char *)&g3 != 0) {
        // 0x1100
        int64_t result; // rax
        return result;
    }
    if (*(int64_t *)0x3fd8 != 0) {
        // 0x10db
        __cxa_finalize((int64_t *)*(int64_t *)0x4020);
    }
    int64_t result2 = deregister_tm_clones(); // 0x10e8
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x1110 - 0x1111
int64_t frame_dummy(void) {
    // 0x1110
    int64_t result; // rax
    return result;
}

// Address range: 0x1113 - 0x1119
int64_t function_1113(void) {
    // 0x1113
    return register_tm_clones();
}

// Address range: 0x1119 - 0x1143
// Demangled:     func(int)
int64_t _Z4funci(int64_t a1) {
    // 0x1119
    return (int32_t)((uint64_t)(0x30c30c31 * a1) / 0x100000000) / 8 - ((int32_t)a1 >> 31);
}

// Address range: 0x1143 - 0x1158
int main(int argc, char ** argv) {
    // 0x1143
    _Z4funci(7);
    return 0;
}

// Address range: 0x1160 - 0x1161
int64_t __libc_csu_init(void) {
    // 0x1160
    int64_t result; // rax
    return result;
}

// Address range: 0x1163 - 0x11c5
int64_t function_1163(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0x118c
    if (((int64_t)&g2 - (int64_t)&g1) / 8 != 0) {
        int64_t v1 = 0; // 0x11ad2
        while (v1 + 1 != ((int64_t)&g2 - (int64_t)&g1) / 8) {
            // 0x11a0
            v1++;
        }
    }
    // 0x11b6
    return result;
}

// Address range: 0x11d0 - 0x11d1
int64_t __libc_csu_fini(void) {
    // 0x11d0
    int64_t result; // rax
    return result;
}

// Address range: 0x11d3 - 0x11d5
int64_t function_11d3(void) {
    // 0x11d3
    int64_t result; // rax
    return result;
}

// Address range: 0x11d8 - 0x11d9
int64_t _fini(void) {
    // 0x11d8
    int64_t result; // rax
    return result;
}

// Address range: 0x11db - 0x11e5
int64_t function_11db(void) {
    // 0x11db
    int64_t result; // rax
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.2.0)
// Detected language: C++
// Detected functions: 17
// Decompilation date: 2019-10-28 15:23:22
