name:                crypto-fraud
version:             0.1.0.0
github:              "keirahaskins/crypto-fraud"
license:             BSD3
author:              "Keira Haskins"
maintainer:          "wasp@unm.edu"
copyright:           "NA"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            NA

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/keirahaskins/crypto-fraud#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  crypto-fraud-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-fraud

tests:
  crypto-fraud-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-fraud
